### ISSUE TITLE
This is garbage

### ISSUE THREAD

**Issue by pukpr** [bobf34/GlobalWarming#1]
A 99-year moving average filter?   LOL

**Comment by bobf34** [comment]
Paul, why do you say it's garbage?  Without a specific objection your comment is just useless noise, and frankly, you come across as someone who is not serious, and who is also lacking in scientific curiosity.  I've spent the better part of a year figuring out why 99-years is important and I can tell you that the results are not a spurious correlation.  LOL is not a scientific argument, it's the response I'd expect from a weak-minded, useful idiot.   Are you a weak-minded useful idiot?  If not, what are your specific objections to the model, and the results?

**Comment by pukpr** [comment]
Yes, I'm a weak-minded idiot. All the rapid variation is due to climate indices such as ENSO. I model ENSO based on tidal cycles and apply no filtering at all. A filter does what it's name implies -- it filters out all useful information. This is a model against data from Darwin which is an ENSO indicator

![](https://user-images.githubusercontent.com/2855758/255753966-f68ecae2-3a5f-474b-b32b-a9d0a87f7fde.png)

**Comment by bobf34** [comment]
> Yes, I'm a weak-minded idiot. All the rapid variation is due to climate indices such as ENSO. I model ENSO based on tidal cycles and apply no filtering at all. A filter does what it's name implies -- it filters out all useful information. This is a model against data from Darwin which is an ENSO indicator
> 
> image removed

I'm not going to spend a lot of time on your model, but it appears to be a parametric harmonic model, and from the plot below, your model appears to diverge rather quickly outside of the training areas.  Even in the plot you included, you seem to have missed a rather significant and well-documented ENSO event in the late 1800s. 

Your filter comment is especially curious as in the training of your model I suspect you're choosing what information to include, and what information to _filter out_ based on thresholds, or some form of PCA.  

The filter in my model performs three functions, two of which I'll describe now, the third will be public when I release my paper.  First the filter removes non-coherent energy from the sunspot data, which is a proxy for solar activity, not the solar activity itself, so  I'm not throwing anything useful away.  Second, the filter also models much of the earth's response to solar forcing.   

![](https://user-images.githubusercontent.com/2855758/235048554-27a17c1e-061a-49cd-b2e4-4ed4a5e2ec4e.png)

**Comment by pukpr** [comment]
Keep up the fantasy that a small perturbation in solar output due to sunspots can compare with the massive predictable modulation that occurs on an annual basis.  Seasonal and tidal forces are acting on the subsurface thermocline. This is the hypothesis of a few ex-NASA-JPL scientists, a group at Ohio State, and myself.

Start with this one by Lin at Ohio State:
https://www.nature.com/articles/s41598-019-49678-w

![](https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41598-019-49678-w/MediaObjects/41598_2019_49678_Fig1_HTML.png)

Sunspots are secondary factors at best. I can model all the climate indices and more with a tidal approach, and perhaps the small discrepancies can be reconciled with solar perturbations, but I really don't care at this point because the foundational model is solved.

**Comment by bobf34** [comment]
Perhaps you can model climate indices, but that's just weather, and I'm not really addressing how energy moves around the earth, though I have noticed a correlation between major El Niño events and solar forcing.  This is just a casual observation, not a study, but the major events seem to occur a variable amount of time after the temperature anomalies in the prediction.  If global temperatures have been stable, then it can take a decade before the event, while if temperatures are rising, the event occurs more quickly.  Also, the event occurs after the forcing begins leveling off, or dropping.  Again, this is just a casual observation.  This fails for 1915, but your model seems to suggest that the temperature spike in 1915 was stronger than recorded.  I also wouldn't have expected a major event in 1972.

When I was playing around with sunspot proxy data based on 14C to extend temperature predictions further back in time I found an anomaly that suggested a major El Niño event in the early 1870's.  After searching the web I found that not only was there an event, but that it's credited with killing 50 million people.  Further, as my model can predict a few years into the future, I predicted that this year's ENSO event, if it even occurs, will not be strong;  the solar forcing I've observed with other strong events is not present.  So far, my off-the-cuff prediction seems to be accurate.  

The sunspot and proxy data are not accurate prior to 1800, so temperature predictions prior to 1900 are not accurate, but they are suggestive.  

![](https://localartist.org/media/1873.png)

You've seem to think that your _opinion_ on solar activity and its effect on global climate is scientific fact when there is, in fact, is a long and ongoing debate on the levels of total solar irradiance, even over the last four solar cycles, and there's also a possibility that solar magnetic flux plays a role.  My results do not suggest that small variations in sunspots are responsible.  In fact these small fluctuations are heavily attenuated by the earth's response. It's the larger variations in solar activity driven by solar cycles longer than 50 years that drives climate change.

As you've not made any substantive comments on the sunspot-based model, and have chosen to completely ignore the amazingly accurate temperature predictions, I'm going to close this issue and ask that you refrain from opening another unless you find an actual defect in the code. 

I suggest if you have an interest that you check back over the next few months.  I'm working on a paper that explains my results, and will post a link here as soon as it's available to the public.

Good luck with your work.
